name: Build Turtle (Ubuntu)

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
            sudo apt-get update
            sudo apt-get install -y cmake g++
            sudo apt install libglfw3-dev
            python3 -m pip install matplotlib

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: turtle-linux
          path: build/libturtle.so